name = "lustre"
version = "3.0.8"

description = "An Elm-inspired framework for building web apps in Gleam!"
licences = ["MIT"]
repository = { type = "github", user = "lustre-labs", repo = "lustre" }
links = [
  { title = "Website", href = "https://lustre.build" },
  { title = "Sponsor", href = "https://github.com/sponsors/hayleigh-dot-dev" },
]

[dependencies]
gleam_stdlib = "~> 0.31"
