name = "lustre"
version = "3.0.0-rc.4"

description = "A framework for building web apps - powered by Gleam and React!"
licences = ["MIT"]
links = [{ title = "Buy me a coffee?", href = "https://github.com/sponsors/hayleigh-dot-dev" }]
repository = { type = "github", user = "hayleigh-dot-dev", repo = "gleam-lustre" }
target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.30"
funtil = "~> 1.0"

