name = "lustre_animation"
version = "0.2.0"
description = "Animations for lustre, utilizing JS requestAnimationFrame"
target = "javascript"
licenses = ["MIT"]
repository = { type = "custom", url = "https://git.chmeee.org/lustre_animation" }

[dependencies]
gleam_stdlib = "~> 0.30"
lustre = { path = "../../lib" }


[dev-dependencies]
gleeunit = "~> 0.10"
