name = "lustre_websocket"
version = "0.6.0"
target = "javascript"

licences = ["MIT"]
description = "Web Socket requests from lustre"
repository = { type = "custom", url = "https://git.chmeee.org/lustre_websocket" }
links = [
    { title = "Package", href = "https://hex.pm/packages/lustre_websocket" },
]

[dependencies]
gleam_stdlib = "~> 0.30"
lustre = { path = "../../lib" }


[dev-dependencies]
gleeunit = "~> 0.10"